#Listener Config:
http.internal.host=0.0.0.0
http.internal.port=8081

#Email SMTP Config:
smtp.host=smtp.gmail.com
smtp.port=587


#API ID:
api.id=21106865

#Twilio Config:
twilio.baseURI=https://api.twilio.com