#Email SMTP Config:
smtp.user=![pwQd8pMEUAbdeuwCbdNOnMzuzmZyVdrb4pbvbVWteKI=]
smtp.password=![QQ66ngTsClFOL2Kang/YiqOJXNcmWmcTWzP+kRdLk9A=]
smtp.to.user=![3m3LGcPYrL0YA3pChalo7S1FDN2c/eTigMd7A22zvaA=]

#Anypoint Paltform Creds:
anypoint.platform.client_id=![vwoeRHAKAVVoDvCd5c3R6XVaImnPgPOkvGOKTghx+wmnA8pJqlc95l7R1DtALkO9]
anypoint.platform.client_secret=![v1drdiuKux78Ji1nhHmT8ZCznb0ry5KyDSP92zeDw33vpIAcjCTCefdnm1kZR7+g]

#Twilio Config:
twilio.user=![J4PX8pF7EH1bw25N71zTVCPqmHjFlCOC4ySMX297qM7skczh2e97waX9mo8XBgcZ]
twilio.password=![FStbDveaMRsy4vrExgT03xsC2LhusBwb8XV6cx8aL/SKfADOLQ6fvQUamHbLNH8y]
twilio.form=![CNlgie65wt5V9GrmPakSEQ==]
twilio.to=![0VptVbzIpxQaVHY7DWzCqg==]
