#Email SMTP Config:
smtp.user=![pwQd8pMEUAbdeuwCbdNOnMzuzmZyVdrb4pbvbVWteKI=]
smtp.password=![QQ66ngTsClFOL2Kang/YiqOJXNcmWmcTWzP+kRdLk9A=]
smtp.to.user=![BjrJQVOq5huv4oFjlS06uZuki8zlkqKURvOK5EhxjBFdTGuXUTt3U5FrBGRT/Uj7]

#Anypoint Paltform Creds:
anypoint.platform.client_id=![0M6uWXX+a+hgizmPS0ddRuJBTo1WV8pYAMv91iY1l86sH1U0oHFsZ5f8NHyE14Pu]
anypoint.platform.client_secret=![RLO1GOddArrJ9QD6LTavT/mqoNEchOszHkZAdmkq1cJSuj2SowXKCgRO11Zc8uIH]

#Twilio Config:
twilio.user=![J4PX8pF7EH1bw25N71zTVCPqmHjFlCOC4ySMX297qM7skczh2e97waX9mo8XBgcZ]
twilio.password=![FStbDveaMRsy4vrExgT03xsC2LhusBwb8XV6cx8aL/SKfADOLQ6fvQUamHbLNH8y]
twilio.form=![76ZnUAKptGhI4a71AKOe3Q==]
twilio.to=![0VptVbzIpxQaVHY7DWzCqg==]
